# Always use the compose file from the current release:
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
# Main branch may not match the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:$
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu
    volumes:
      - immich-photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      immich-net:
        ipv4_address: 172.19.0.10
    labels:
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
      net.unraid.docker.webui: http://[IP]:[PORT:2283]
      folder.view: immich
      net.unraid.docker.managed: 'composeman'

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:$
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      immich-net:
        ipv4_address: 172.19.0.11
    labels:
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
      folder.view: immich
      net.unraid.docker.managed: 'composeman'

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      immich-net:
        ipv4_address: 172.19.0.12
    labels:
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/redis.png'
      folder.view: immich
      net.unraid.docker.managed: 'composeman'

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.3.0
    environment:
      POSTGRES_PASSWORD: $
      POSTGRES_USER: $
      POSTGRES_DB: $
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      immich-net:
        ipv4_address: 172.19.0.13
    labels:
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/postgres.png'
      folder.view: immich
      net.unraid.docker.managed: 'composeman'

networks:
  immich-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

volumes:
  model-cache:
    driver: local
    driver_opts:
      type: none
      device: /mnt/user/appdata/immich/config
      o: bind

  immich-photos:
    driver: local
    driver_opts:
      type: none
      device: /mnt/user/appdata/immich/photos
      o: bind

  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/user/appdata/immich/database/postgres
      o: bind

  redis-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/user/appdata/immich/database/redis
      o: bind
